### ISSUE TITLE
请问    与主界面的下拉刷新冲突 怎么解决呢？

### ISSUE THREAD

**Issue by i91h1r** [oubowu/YinyuetaiPlayer#2]
还有假如主界面是由fragment framlayout 替换的，播放界面不能覆盖住底部导航栏 这两个怎么解决额？

**Comment by oubowu** [comment]
1、下拉刷新不会冲突的，只要是你操作播放页面的时候，事件是不会传递到下拉刷新的，除非你把这个控件放在了下拉刷新布局里面
2、播放界面就是个控件来的，设置与0底部导航栏对齐即可

**Comment by i91h1r** [comment]
第一个解决了。 第二个设置与0底部导航栏对其是什么意思额。

**Comment by oubowu** [comment]
底部导航栏是什么控件？
