### ISSUE TITLE
简书的链接失效了,还有别的链接吗？

### ISSUE THREAD

**Issue by zzzsssbo** [oubowu/YinyuetaiPlayer#3]
简书的链接失效了,还有别的链接吗？

**Comment by oubowu** [comment]
是的 因为那个简书之前有那个侮辱程序员的帖子事件 我直接删除账号了，你看这里https://oubowu.github.io/

**Comment by zzzsssbo** [comment]
@oubowu  可以可以  支持你删号，我也卸载app了
